codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%

ignore:
  - "src/wasm_interface.rs"  # WASM-only code, not covered by native tests
  - "tests/**/*"
  - "examples_old/**/*"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
